// Lightweight RRULE expander — supports patterns generated by RecurrencePicker.
// Not a full RFC 5545 implementation; covers DAILY, WEEKLY, MONTHLY, YEARLY
// with INTERVAL, BYDAY (ordinal + plain), BYMONTHDAY, BYSETPOS, UNTIL, COUNT.

const DOW_MAP: Record<string, number> = { SU: 0, MO: 1, TU: 2, WE: 3, TH: 4, FR: 5, SA: 6 }

function lDate(s: string): Date {
  const [y, m, d] = s.split('-').map(Number)
  return new Date(y, m - 1, d)
}
function fmtD(d: Date): string {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
}
function plusDays(d: Date, n: number): Date {
  return new Date(d.getFullYear(), d.getMonth(), d.getDate() + n)
}

export function expandRRule(
  rule:       string,
  baseDate:   string,
  rangeStart: string,
  rangeEnd:   string,
  exceptions: string[] = [],
): string[] {
  const r = rule.replace(/^RRULE:/i, '')
  const p: Record<string, string> = {}
  r.split(';').forEach(seg => { const [k, v] = seg.split('='); if (k && v !== undefined) p[k] = v })

  const freq       = p.FREQ ?? 'WEEKLY'
  const interval   = Math.max(1, parseInt(p.INTERVAL ?? '1'))
  const byDayStrs  = p.BYDAY ? p.BYDAY.split(',') : []
  const byMonthDay = p.BYMONTHDAY ? parseInt(p.BYMONTHDAY) : null
  const byMonth    = p.BYMONTH    ? parseInt(p.BYMONTH)    : null
  const bySetPos   = p.BYSETPOS   ? parseInt(p.BYSETPOS)   : null
  const maxCount   = p.COUNT ? parseInt(p.COUNT) : Infinity
  // Normalise UNTIL from YYYYMMDD or YYYYMMDDTHHMMSSZ
  const untilRaw   = p.UNTIL ?? null
  const until      = untilRaw
    ? untilRaw.slice(0, 8).replace(/(\d{4})(\d{2})(\d{2})/, '$1-$2-$3')
    : null

  const byDays = byDayStrs.map(bd => {
    const m = bd.match(/^([+-]?\d+)?([A-Z]{2})$/)
    if (!m) return null
    return { ordinal: m[1] != null ? parseInt(m[1]) : null, dow: DOW_MAP[m[2]] ?? 0 }
  }).filter((x): x is { ordinal: number | null; dow: number } => x !== null)

  const base    = lDate(baseDate)
  const rsD     = lDate(rangeStart)
  const reD     = lDate(rangeEnd)
  const untilD  = until ? lDate(until) : null
  const endD    = untilD && untilD < reD ? untilD : reD
  const exSet   = new Set(exceptions)
  const results: string[] = []
  let n = 0

  function push(d: Date) {
    if (n >= maxCount || d < rsD || d > endD || d < base) return
    const ds = fmtD(d)
    if (!exSet.has(ds)) { results.push(ds); n++ }
  }

  if (freq === 'DAILY') {
    for (let cur = new Date(base); cur <= endD && n < maxCount; cur = plusDays(cur, interval)) push(cur)

  } else if (freq === 'WEEKLY') {
    if (byDays.length === 0) {
      for (let cur = new Date(base); cur <= endD && n < maxCount; cur = plusDays(cur, interval * 7)) push(cur)
    } else {
      const baseSun = plusDays(base, -base.getDay())
      for (let ws = new Date(baseSun); ws <= endD && n < maxCount; ws = plusDays(ws, interval * 7)) {
        const week = byDays.map(({ dow }) => plusDays(ws, dow)).sort((a, b) => a.getTime() - b.getTime())
        for (const c of week) { if (n < maxCount) push(c) }
      }
    }

  } else if (freq === 'MONTHLY') {
    let y = base.getFullYear(), m = base.getMonth()
    while (n < maxCount) {
      const dim = new Date(y, m + 1, 0).getDate()
      const candidates: Date[] = []

      if (byMonthDay !== null) {
        const day = byMonthDay > 0 ? byMonthDay : dim + byMonthDay + 1
        if (day >= 1 && day <= dim) candidates.push(new Date(y, m, day))
      } else if (bySetPos !== null && byDays.length > 0) {
        const all = Array.from({ length: dim }, (_, i) => new Date(y, m, i + 1))
          .filter(d => d.getDay() === byDays[0].dow)
        const idx = bySetPos > 0 ? bySetPos - 1 : all.length + bySetPos
        if (idx >= 0 && idx < all.length) candidates.push(all[idx])
      } else if (byDays.length > 0 && byDays[0].ordinal !== null) {
        const { ordinal, dow } = byDays[0]
        const all = Array.from({ length: dim }, (_, i) => new Date(y, m, i + 1)).filter(d => d.getDay() === dow)
        const idx = ordinal > 0 ? ordinal - 1 : all.length + ordinal
        if (idx >= 0 && idx < all.length) candidates.push(all[idx])
      } else {
        const day = base.getDate()
        if (day <= dim) candidates.push(new Date(y, m, day))
      }

      if (candidates.length > 0 && candidates[0] > endD) break
      for (const c of candidates) push(c)

      m += interval
      if (m > 11) { y += Math.floor(m / 12); m = ((m % 12) + 12) % 12 }
      if (new Date(y, m, 1) > endD) break
    }

  } else if (freq === 'YEARLY') {
    for (let yr = base.getFullYear(); n < maxCount; yr += interval) {
      const occ = byMonth != null && byMonthDay != null
        ? new Date(yr, byMonth - 1, byMonthDay)
        : new Date(yr, base.getMonth(), base.getDate())
      if (occ > endD) break
      push(occ)
    }
  }

  return results
}

// Human-readable summary of an RRULE string given the base event date.
export function rruleLabel(rule: string, baseDate: string): string {
  if (!rule) return 'Never'
  const r = rule.replace(/^RRULE:/i, '')
  const p: Record<string, string> = {}
  r.split(';').forEach(seg => { const [k, v] = seg.split('='); if (k && v !== undefined) p[k] = v })

  const DAY_NAMES = ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday']
  const MON_SHORT = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec']
  const ORDINALS  = ['1st','2nd','3rd','4th','5th']

  const [y, m, d] = baseDate.split('-').map(Number)
  const base      = new Date(y, m - 1, d)
  const interval  = parseInt(p.INTERVAL ?? '1')
  const freq      = p.FREQ ?? 'WEEKLY'

  if (freq === 'DAILY' && interval === 1) return 'Every day'
  if (freq === 'DAILY') return `Every ${interval} days`

  if (freq === 'WEEKLY') {
    const byday = p.BYDAY ?? ''
    if (byday === 'MO,TU,WE,TH,FR') return 'Every weekday (Mon–Fri)'
    const dayName = DAY_NAMES[base.getDay()]
    if (interval === 1) return `Every week (on ${dayName})`
    if (interval === 2) return `Every 2 weeks (on ${dayName})`
    return `Every ${interval} weeks (on ${dayName})`
  }

  if (freq === 'MONTHLY') {
    if (p.BYMONTHDAY) {
      const n = parseInt(p.BYMONTHDAY)
      return `Every month (on the ${ORDINALS[n - 1] ?? `${n}th`})`
    }
    const dowMap: Record<string, string> = { SU:'Sun',MO:'Mon',TU:'Tue',WE:'Wed',TH:'Thu',FR:'Fri',SA:'Sat' }
    if (p.BYSETPOS && p.BYDAY) {
      const pos = parseInt(p.BYSETPOS)
      return `Every month (on the ${ORDINALS[pos - 1] ?? `${pos}th`} ${dowMap[p.BYDAY] ?? p.BYDAY})`
    }
    if (p.BYDAY) {
      const match = p.BYDAY.match(/^([+-]?\d+)([A-Z]{2})$/)
      if (match) {
        const ord = parseInt(match[1])
        return `Every month (on the ${ORDINALS[ord - 1] ?? `${ord}th`} ${dowMap[match[2]] ?? match[2]})`
      }
    }
    return 'Every month'
  }

  if (freq === 'YEARLY') return `Every year (on ${MON_SHORT[m - 1]} ${d})`
  return rule
}
